In [1]:
pip install mysql-connector-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.32-cp39-cp39-manylinux1_x86_64.whl (23.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.5/23.5 MB 24.6 MB/s eta 0:00:00
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in /usr/local/lib/python3.9/dist-packages (from mysql-connector-python) (3.19.6)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.0.32

In [2]:
#Mysql local
import mysql.connector as mysql
import pandas as pd

In [3]:
myconn = mysql.connect(host='sql12.freesqldatabase.com',
                       database='sql12604228', 
                       user='sql12604228', 
                       password='FT4AaDU9kD')

In [4]:
# Membuat objek cursor
mycursor = myconn.cursor()

# Mengambil data dari tabel
mycursor.execute("SELECT petallength FROM iris")

# Mengambil semua hasil query
result = mycursor.fetchall()

# Menutup kursor dan koneksi
mycursor.close()
myconn.close()

# Membuat DataFrame dari hasil query
df2 = pd.DataFrame(result, columns=["petallength"])

# Menampilkan data
print(df2)

    petallength
0           1.4
1           1.4
2           1.3
3           1.5
4           1.4
..          ...
145         5.2
146           5
147         5.2
148         5.4
149         5.1

[150 rows x 1 columns]