# Tugas 2 Memanggil data iris di 4 database yang berbeda

Sepal length posgresql local)

In [ ]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\acer\anaconda3\lib\site-packages (2.9.5)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import psycopg2
connection = psycopg2.connect(user='postgres',
                              password='akuanakbaik',
                              host='127.0.0.1',
                              port='5432',
                              database='prosain{210411100112}')

In [ ]:
import pandas as pd

In [ ]:
# Membuat objek cursor
cursor = connection.cursor()

# Mengambil data dari tabel
cursor.execute("SELECT sepallength FROM Iris")

# Membuat DataFrame dari hasil query
df = pd.read_sql("SELECT sepallength FROM Iris", connection)

# Menampilkan data
print(df)

     sepallength
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
..           ...
145          6.7
146          6.3
147          6.5
148          6.2
149          5.9

[150 rows x 1 columns]

Sepal width  	: di postgeql elephantsql)

In [ ]:
import psycopg2
import pandas as pd

# Connection parameters, yours will be different
param_dic = {
    "host"      : "trumpet.db.elephantsql.com",
    "database"  : "xtzkuaqv",
    "user"      : "xtzkuaqv",
    "password"  : "OupjNX9j0ny4IIeAWJpC014w6HPFTA38"
}

def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Mengambil data dari cursor
    rows = cursor.fetchall()
    cursor.close()
    
    # Membuat DataFrame dari hasil query
    df = pd.DataFrame(rows, columns=column_names)
    
    return df

# Membuat koneksi database
conn = connect(param_dic)

# Menjalankan query dan menghasilkan DataFrame
query = "SELECT sepal_w FROM iris"
column_names = ["sepal_w"]
df1 = postgresql_to_dataframe(conn, query, column_names)

# Menampilkan data
print(df1)

Connecting to the PostgreSQL database...
Connection successful
     sepal_w
0        3.5
1        3.0
2        3.2
3        3.1
4        3.6
..       ...
145      3.0
146      2.5
147      3.0
148      3.4
149      3.0

[150 rows x 1 columns]

Petal length di mysql local

In [ ]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\acer\anaconda3\lib\site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\acer\anaconda3\lib\site-packages (from mysql-connector-python) (3.20.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#Mysql local
import mysql.connector as mysql
import pandas as pd

In [ ]:
myconn = mysql.connect(host='sql12.freesqldatabase.com',
                       database='sql12604228', 
                       user='sql12604228', 
                       password='FT4AaDU9kD')

In [ ]:
# Membuat objek cursor
mycursor = myconn.cursor()

# Mengambil data dari tabel
mycursor.execute("SELECT petallength FROM iris")

# Mengambil semua hasil query
result = mycursor.fetchall()

# Menutup kursor dan koneksi
mycursor.close()
myconn.close()

# Membuat DataFrame dari hasil query
df2 = pd.DataFrame(result, columns=["petallength"])

# Menampilkan data
print(df2)

    petallength
0           1.4
1           1.4
2           1.3
3           1.5
4           1.4
..          ...
145         5.2
146           5
147         5.2
148         5.4
149         5.1

[150 rows x 1 columns]

Petal width , class di sql server local)

In [ ]:
pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\acer\anaconda3\lib\site-packages (4.0.0-unsupported)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pyodbc 
import pandas as pd

In [ ]:
cnxn_str = ("Driver={ODBC Driver 17 for SQL Server};"
            "Server=LAPTOP-SOC00JA3\SQLEXPRESS;" 
            "Database=prosain{210411100112};Trusted_Connection=yes")

cnxn = pyodbc.connect(cnxn_str)
cursor = cnxn.cursor()	
cursor.execute("Select petalwidth, class From iris")
row = cursor.fetchall() 
cursor.close()

data=[]
for i in row:
    data.append([i[0], i[1].strip('"')])

# Membuat DataFrame dari hasil query
df_sqlServer = pd.DataFrame(data, columns=['petalwidth', 'class'])

# Menyalin DataFrame ke variabel baru
df3 = df_sqlServer

# Menampilkan data
print(df3)

     petalwidth           class
0           0.2     Iris-setosa
1           0.2     Iris-setosa
2           0.2     Iris-setosa
3           0.2     Iris-setosa
4           0.2     Iris-setosa
..          ...             ...
145         2.3  Iris-virginica
146         1.9  Iris-virginica
147         2.0  Iris-virginica
148         2.3  Iris-virginica
149         1.8  Iris-virginica

[150 rows x 2 columns]

## Menggabungkan 4 database

In [ ]:
data = pd.concat([df,df1,df2,df3], axis=1)

In [ ]:
print(data)

     sepallength  sepal_w petallength  petalwidth           class
0            5.1      3.5         1.4         0.2     Iris-setosa
1            4.9      3.0         1.4         0.2     Iris-setosa
2            4.7      3.2         1.3         0.2     Iris-setosa
3            4.6      3.1         1.5         0.2     Iris-setosa
4            5.0      3.6         1.4         0.2     Iris-setosa
..           ...      ...         ...         ...             ...
145          6.7      3.0         5.2         2.3  Iris-virginica
146          6.3      2.5           5         1.9  Iris-virginica
147          6.5      3.0         5.2         2.0  Iris-virginica
148          6.2      3.4         5.4         2.3  Iris-virginica
149          5.9      3.0         5.1         1.8  Iris-virginica

[150 rows x 5 columns]

## Pre-prosessing

In [ ]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB

In [ ]:
#preprosessing

X=data.iloc[:,0:4].values
y=data.iloc[:,4].values

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

## Metode KNN

In [ ]:
#knn

knn_clf = KNeighborsClassifier(n_neighbors=9)
knn_clf.fit(X_train,y_train)

y_pred = knn_clf.predict(X_test)

accuracy_knn=round(accuracy_score(y_test,y_pred),3)
print(accuracy_knn)

0.978

## Metode Naive Bayes

In [ ]:
# naive bayes

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
YY_pred = gaussian.predict(X_test)
accuracy_nb=round(accuracy_score(y_test,YY_pred)* 100, 2)
print(accuracy_nb)

100.0

## Model KNN

In [ ]:
# buat model knn

import pickle

with open('knnB_pickle','wb') as r:
    pickle.dump(knn_clf,r)

## Model Naive Bayes

In [ ]:
#buat model naive bayes
import pickle

with open('nb1_pickle','wb') as r:
    pickle.dump(gaussian,r)